// <auto-generated />
namespace Code11.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Third4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Third4));
        
        string IMigrationMetadata.Id
        {
            get { return "201801141218568_Third-4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
